# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-27 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_report_published_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fistName', models.CharField(max_length=32)),
                ('lastName', models.CharField(max_length=32)),
                ('user_id', models.BigIntegerField()),
                ('bio', models.TextField()),
            ],
        ),
    ]
