# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-05 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180416_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='uudid',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
