# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-05 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_report_uudid'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='image_name',
            field=models.CharField(default='23', max_length=600),
            preserve_default=False,
        ),
    ]
